telegram_enabled="true"
telegram_token="${TELEGRAM_BOT_TOKEN}"
telegram_as_attachment="false"
telegram_as_photo="true"
telegram_channel="${TELEGRAM_BOT_CHAT_ID}"
telegram_caption="%hostname, %datetime"
telegram_socks5_enabled="false"
